# These are supported funding model platforms

github: aleksbrzoska/tunezeal
patreon: tunezeal
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
custom: paypal.me/unlockpage
